# This is a basic workflow to help you get started with Actions

name: PubPage

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        path: src
    - uses: actions/checkout@v2
      with:
        repository: 'comira/dist'
        path: dist
    - name: LS
      run: |
        echo 
        ls ./
        ls ./src/
        ls ./dist/
    - name: configSSH
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: configGit
      run: |
        git config --global user.email "test@github.com"
        git config --global user.name "test"
    - name: mkFile
      run: |
        cd dist
        echo "Hello World" > test.md
        ls ./
        git add .
        git commit -am "Update"
        git push origin master
